core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moneyaccount.urls', namespace="mc"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

moneyaccount/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from moneyaccount.views import dashboard, accounts, transactions, reports


app_name = "mc"

urlpatterns = [
    path('dashboard/', dashboard.DashboardView.as_view(), name="dashboard"),
    # Money Accounts
    path('my-accounts/', accounts.MoneyAccountListView.as_view(), name="account-list"),
    path('my-accounts/create/', accounts.MoneyAccountCreateView.as_view(), name="account-create"),
    path('my-accounts/update/<str:name>/<uuid:pk>/', accounts.MoneyAccountUpdateView.as_view(), name="account-update"),
    path('my-accounts/<str:name>/<uuid:pk>/', accounts.MoneyAccountDetailView.as_view(), name="account-detail"),
    path('my-accounts/delete/<str:name>/<uuid:pk>/', accounts.MoneyAccountDeleteView.as_view(), name="account-delete"),
    path('make-main/<uuid:account_pk>/', accounts.make_main, name="make-main"),
    # Transactions
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/', transactions.TransactionListView.as_view(), name="transaction-list"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/create/', transactions.TransactionCreateView.as_view(), name="transaction-create"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/delete/<uuid:pk>', transactions.TransactionDeleteView.as_view(), name="transaction-delete"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/detail/<uuid:pk>', transactions.TransactionDetailView.as_view(), name="transaction-detail"),
    # Export Reports
    path('reports/', reports.ExportTransactionListView.as_view(), name="report-list"),
    path('reports/export/<uuid:account_pk>/', reports.ExportTransactionView.as_view(), name="export-report"),
    # User Accounts
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True) ,name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', dashboard.UserCreateView.as_view(), name='register'),
]

moneyaccount/models.py
import random
import uuid

from django.db import models
from django.core.validators import MinValueValidator
from django.template.defaultfilters import slugify
from django.conf import settings
from django.urls import reverse

def defaultname():
    names = ["Cool Account", "Smile", "Blank", "Give Me a Name", "Unknown", "Anonymous"]
    return random.choice(names)

def make_uuid():
    return uuid.uuid4()

class AccountTypes(models.TextChoices):
    """Enumeration for the types of questions"""

    PERSONAL = "personal", "Personal" 
    SAVINGS = "savings", "Savings" 
    INVESTING = "investing", "Investing" 
    OTHER = "other", "Other" 

class MoneyAccount(models.Model):
    id = models.UUIDField(primary_key=True, default=make_uuid)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    total_balance = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0)])
    name = models.CharField(max_length=255, null=True, blank=True, default=defaultname)
    bank = models.CharField(max_length=255, null=True, blank=True)
    account_type = models.CharField(max_length=50, null=False, choices=AccountTypes.choices, default=AccountTypes.PERSONAL)
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class TransactionTypes(models.TextChoices):
    """Enumeration for the types of questions"""

    PAYMENT = "payment", "Payment" 
    DEPOSIT = "deposit", "Deposit" 

class Transaction(models.Model):
    id = models.UUIDField(primary_key=True, default=make_uuid)
    title = models.CharField(max_length=255)
    note = models.TextField(null=True, blank=True)
    amount = models.DecimalField(max_digits=7, decimal_places=2, validators=[MinValueValidator(0)])
    date = models.DateField()
    account = models.ForeignKey(MoneyAccount, on_delete=models.CASCADE, related_name="transactions")
    current_balance = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0)])
    new_balance = models.DecimalField(max_digits=8, decimal_places=2, default=0, validators=[MinValueValidator(0)])
    transaction_type = models.CharField(max_length=50, null=False, choices=TransactionTypes.choices)
    

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.title

moneyaccount/forms/filters.py
from django import forms


class TransactionFilterForm(forms.Form):

    filter = forms.CharField(max_length=15, required=False)
    search = forms.CharField(max_length=255, required=False)

    class Meta:
        fields = ("filter", "search")

    def clean(self):
        super().clean()

        choices = ["month", "week", 'today']
        initial_errors = self.errors.as_data()

        if "filter" not in initial_errors:
            filter = self.cleaned_data["filter"]
            if filter not in choices and filter:
                self.add_error("filter", "Invalid Choice")

moneyaccount/views/dashboard.py
import datetime
import imp
from threading import main_thread
from unicodedata import decimal
from urllib import request
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages

from moneyaccount.forms.filters import TransactionFilterForm
from moneyaccount.forms.accounts import RegistrationForm
from moneyaccount.models import MoneyAccount, Transaction


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'
    
    def get_context_data(self, **kwargs):
        """get context"""
        context = super().get_context_data(**kwargs)

        valid = False
        try:
            all_transactions = Transaction.objects.filter(account__user=self.request.user)
            main_moneyaccount = MoneyAccount.objects.get(Q(is_main=True) & Q(user=self.request.user))
        except MoneyAccount.DoesNotExist:
            main_moneyaccount = None

        form = TransactionFilterForm(self.request.GET.dict())
        if form.is_valid():
            valid = True
            
            filter = form.cleaned_data["filter"]
            search = form.cleaned_data["search"]

            if filter == "today":
                date = datetime.date.today()
                all_transactions = all_transactions.filter(date__gte=date)

            if filter == "week":
                date = datetime.date.today() - datetime.timedelta(days=7)
                all_transactions = all_transactions.filter(date__gte=date)

            if filter == "month":
                date = datetime.date.today() - datetime.timedelta(days=30)
                all_transactions = all_transactions.filter(date__gte=date)

            if search:
                all_transactions =all_transactions.filter(
                    Q(title__icontains=search) |
                    Q(amount__icontains=search) | 
                    Q(account__name__icontains=search)
                )

        context["transactions"] = all_transactions[:15]
        context["main_account"] = main_moneyaccount
        context["valid"] = valid
        return context

class UserCreateView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('mc:login')

    def form_valid(self, form):
        user = form.save(self.request)

        # Success message 
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'User Created!'
        ) 
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(reverse_lazy('mc:dashboard'))
        return super().dispatch(request, *args, **kwargs)

moneyaccount/views/reports.py
import csv
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from moneyaccount.models import MoneyAccount, Transaction


class ExportTransactionListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = MoneyAccount
    template_name = "reports.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def test_func(self):
        my_accounts = self.get_queryset()
        my_accounts_check = [ account.user == self.request.user for account in my_accounts]
        return all(my_accounts_check)

class ExportTransactionView(LoginRequiredMixin, View):
    """Generate CSV file for Transactions"""

    template_name = "transaction/export_transaction.html"
    TRANSACTION_HEADER = [
        'Account Name',
        "Title",
        "Note",
        "Current Balance",
        "Amount",
        "Total",
        "Date",
        "Transaction Type",
    ]

    def get(self, request, *args, **kwargs):
        """get context"""
        context = {
            "accounts": MoneyAccount.objects.filter(user=self.request.user),
        }
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        accounts = MoneyAccount.objects.filter(user=self.request.user)

        for account in accounts:
            if account.name in request.POST:
                file_name = f"{account.name}.csv"
                transactions = account.transactions.order_by("date")
                
                response = None
                if transactions:
                    response = HttpResponse(content_type="text/csv; charset=utf-8-sig")
                    writer = csv.writer(response)
                    writer.writerow(self.TRANSACTION_HEADER)

                    for transaction in transactions:
                        writer.writerow(
                            [
                                account.name,
                                transaction.title,
                                transaction.note,
                                transaction.current_balance,
                                transaction.amount,
                                transaction.new_balance,
                                transaction.date,
                                transaction.transaction_type,
                            ]
                        )

                    response["Content-Disposition"] = f"attachment; filename={file_name}"
                    return response
            return redirect(reverse_lazy("mc:report-list"))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block custom-css %} {% endblock %}

    <title>{% block title %}Financial Manager app{% endblock %}</title>
</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark row justify-content-between p-0 shadow">
        <a class="navbar-brand col-sm-12 col-md-3 col-lg-2 me-0 px-5" href="#">Financial Manager</a>
        <div class="navbar-nav col-sm-12 col-md-4 col-lg-2">
            <div class="nav-item text-center text-nowrap">
                {% if request.user.is_authenticated %}
                <a class="nav-link px-3 fw-bold" href="{% url 'mc:logout' %}">Sign out</a>
                {% else %}
                <a class="nav-link px-3 fw-bold" href="{% url 'mc:login' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item px-3" title="{{request.user.get_username}}">
                            <i class="bi bi-person-fill"></i>
                            <a class="nav-link d-inline {% if '/dashboard/' in url_path %}active{% endif %}"
                                aria-current="page" href="{% url 'mc:dashboard' %}">
                                {{request.user.get_full_name}}
                            </a>
                        </li>
                        <hr>
                        {% endif %}
                        {% with request.get_full_path as url_path %}
                        <li class="nav-item px-3">
                            <a class="nav-link {% if '/dashboard/' in url_path %}active{% endif %}" aria-current="page"
                                href="{% url 'mc:dashboard' %}">
                                <span data-feather="home"></span>
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item px-3">
                            <a class="nav-link {% if '/my-accounts/' in url_path %}active{% endif %}"
                                href="{% url 'mc:account-list' %}">
                                <span data-feather="file"></span>
                                Accounts
                            </a>
                        </li>
                        <li class="nav-item px-3">
                            <a class="nav-link {% if '/reports/' in url_path %}active{% endif %}"
                                href="{% url 'mc:report-list' %}">
                                <span data-feather="bar-chart-2"></span>
                                Reports
                            </a>
                        </li>
                        {% endwith%}
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 my-3 text-muted">
                        <span>Settings</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item px-3">
                            <a class="nav-link" href="{% url 'mc:logout' %}">
                                <span data-feather="file-text"></span>
                                Logout
                            </a>
                        </li>
                        {% else %}
                        <li class="nav-item px-3">
                            <a class="nav-link" href="{% url 'mc:login' %}">
                                <span data-feather="file-text"></span>
                                Login
                            </a>
                        </li>
                        <li class="nav-item px-3">
                            <a class="nav-link" href="{% url 'mc:register' %}">
                                <span data-feather="file-text"></span>
                                Register
                            </a>
                        </li>
                        {% endif %}

                        <li class="nav-item px-3">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Settings(coming soon)
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div
                    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <div class="fw-bold nav-header">{% block nav-title %} {% endblock %}</div>

                    <div class="btn-toolbar mb-2 mb-md-0">
                        {% block nav-buttons %}
                        {% endblock %}
                    </div>
                </div>

                {% block content %}
                {% endblock %}

            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>

</body>

</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static%}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}

{% block title %}Dashboard{% endblock %}

{% block nav-title %}Dashboard {% endblock %}

{% block nav-buttons %}
    {% include 'filter.html' %} 
{% endblock %}

{% block content %}

<div class="d-flex row mt-5 py-3 justify-content-around">
    {% if main_account %}
        <div class="col-sm-12 col-md-12 col-lg-5 px-3 mb-4 main-card bg-light">
            <div>
                <i class="bi bi-bookmark-star-fill main-icon"></i>
            </div>

            <div class="py-4 px-4 my-2 text-center">
                <ul class="dashboard-info">
                    <li><b> Account Name: </b>{{main_account.name|title}}</li>
                    <li><b> Bank: </b>{{main_account.bank}}</li>
                    <li><b> Type: </b>{{main_account.get_account_type_display}}</li>
                </ul>
                <div class="mt-5">
                    <a href="{% url 'mc:account-update' main_account.name main_account.id %}" class="col-6 btn btn-primary fw-bold" type="button">Edit</a>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-5 px-3 mb-4 main-card bg-light">
            <div>
                <i class="bi bi-bookmark-star-fill main-icon"></i>
            </div>
            <div class=" py-4 px-4 my-2 text-center">
                <ul class="dashboard-info">
                    <li><b> Total Balance: </b>{{main_account.total_balance}}</li>
                    <li><b> Total Transactions: </b>{{main_account.transactions.all.count|default:"--"}}</li>
                    <li><b> Latest Transaction: </b>{{main_account.transactions.all.0.date|default:"--"}}</li>
                </ul>
                <div class="mt-5">
                    <a href="{% url 'mc:transaction-list' main_account.name main_account.id%}" class="col-6 btn btn-primary fw-bold" type="button">Transactions</a>
                </div>
            </div>
        </div>
    {% endif%}
</div>


<div class="table-responsive mb-5">
    {% if valid and transactions %}
        <table class="table table-hover table-striped table-sm mb-5 text-center">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Account</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            <tbody class="align-middle">
                {% for transaction in transactions %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{transaction.title}}</td>
                    <td class="{% if transaction.transaction_type == 'payment' %}text-danger{% else %}text-success{% endif %}">{{transaction.amount}}</td>
                    <td>{{transaction.account}}</td>
                    <td>{{transaction.date}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        {% if not valid %}
            <h2 class="text-danger text-center card p-5 bg-light mt-5">Invalid Search Bro...</h2>
        {% else %}
            <h2 class="text-danger text-center card p-5 bg-light mt-5">No Transactions Available...</h2>
        {% endif %}
    {% endif %}
</div>

{% endblock %}

templates/filter.html
<form method="GET">
    <div class="row">
        <div class="col-lg-4 col-lg-4 col-md-4 col-12 my-1">
            <input type="search" class="form-control" name="search" placeholder="Search" aria-label="search">
        </div>
        <div class="btn-group col-lg-4 col-md-4 col-12 my-1">
            <select name='filter' class="btn btn-light" aria-label="filter">
                <option value="" {% if not request.GET.filter %}selected{% endif %}>All</option>
                <option {% if request.GET.filter == "today" %}selected{% endif %} value="today">Today</option>
                <option {% if request.GET.filter == "week" %}selected{% endif %} value="week">Last 7 Dyas</option>
                <option {% if request.GET.filter == "month" %}selected{% endif %} value="month">Last 30 days</option>
            </select>
            <button type="submit" class="btn btn-primary fw-bold">
                Filter
            </button>
        </div>
    </div>
</form>

templates/reports.html
{% extends 'base.html' %}
{% load static%}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block title %}Reports{% endblock %}

{% block nav-title %}Reports {% endblock %}

{% block content %}
    {{valid}}

    <div class="row justify-content-center my-5">
        <div class="col-lg-7 col-md-12 col-sm-12 my-5">
            <div class="card bg-light form-card">
                <div class="card-body">
                    {% for account in object_list %}
                        <form method="POST" action="{% url 'mc:export-report' account.id %}" class="my-5 text-center">
                            {% csrf_token %}
                            <h4 class="fw-bold ">{{account.name}}</h4>
                            <input name="{{account.name}}" value="{{account.name}}" type="hidden">
                            <button {% if not account.transactions.all %}disabled{% endif %} type="submit" class="btn btn-primary col-6 my-1 fw-bold">
                                <i class="bi bi-file-earmark-arrow-down-fill"></i>
                                Download Report
                            </button>
                        </form>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}