core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moneyaccount.urls', namespace="mc"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

moneyaccount/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from moneyaccount.views import dashboard, accounts, transactions, reports


app_name = "mc"

urlpatterns = [
    path('dashboard/', dashboard.DashboardView.as_view(), name="dashboard"),
    # Money Accounts
    path('my-accounts/', accounts.MoneyAccountListView.as_view(), name="account-list"),
    path('my-accounts/create/', accounts.MoneyAccountCreateView.as_view(), name="account-create"),
    path('my-accounts/update/<str:name>/<uuid:pk>/', accounts.MoneyAccountUpdateView.as_view(), name="account-update"),
    path('my-accounts/<str:name>/<uuid:pk>/', accounts.MoneyAccountDetailView.as_view(), name="account-detail"),
    path('my-accounts/delete/<str:name>/<uuid:pk>/', accounts.MoneyAccountDeleteView.as_view(), name="account-delete"),
    path('make-main/<uuid:account_pk>/', accounts.make_main, name="make-main"),
    # Transactions
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/', transactions.TransactionListView.as_view(), name="transaction-list"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/create/', transactions.TransactionCreateView.as_view(), name="transaction-create"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/delete/<uuid:pk>', transactions.TransactionDeleteView.as_view(), name="transaction-delete"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/detail/<uuid:pk>', transactions.TransactionDetailView.as_view(), name="transaction-detail"),
    # Export Reports
    path('reports/', reports.ExportTransactionListView.as_view(), name="report-list"),
    path('reports/export/<uuid:account_pk>/', reports.ExportTransactionView.as_view(), name="export-report"),
    # User Accounts
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True) ,name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', dashboard.UserCreateView.as_view(), name='register'),
]

moneyaccount/models.py
import random
import uuid

from django.db import models
from django.core.validators import MinValueValidator
from django.template.defaultfilters import slugify
from django.conf import settings
from django.urls import reverse

def defaultname():
    names = ["Cool Account", "Smile", "Blank", "Give Me a Name", "Unknown", "Anonymous"]
    return random.choice(names)

def make_uuid():
    return uuid.uuid4()

class AccountTypes(models.TextChoices):
    """Enumeration for the types of questions"""

    PERSONAL = "personal", "Personal" 
    SAVINGS = "savings", "Savings" 
    INVESTING = "investing", "Investing" 
    OTHER = "other", "Other" 

class MoneyAccount(models.Model):
    id = models.UUIDField(primary_key=True, default=make_uuid)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    total_balance = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0)])
    name = models.CharField(max_length=255, null=True, blank=True, default=defaultname)
    bank = models.CharField(max_length=255, null=True, blank=True)
    account_type = models.CharField(max_length=50, null=False, choices=AccountTypes.choices, default=AccountTypes.PERSONAL)
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class TransactionTypes(models.TextChoices):
    """Enumeration for the types of questions"""

    PAYMENT = "payment", "Payment" 
    DEPOSIT = "deposit", "Deposit" 

class Transaction(models.Model):
    id = models.UUIDField(primary_key=True, default=make_uuid)
    title = models.CharField(max_length=255)
    note = models.TextField(null=True, blank=True)
    amount = models.DecimalField(max_digits=7, decimal_places=2, validators=[MinValueValidator(0)])
    date = models.DateField()
    account = models.ForeignKey(MoneyAccount, on_delete=models.CASCADE, related_name="transactions")
    current_balance = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0)])
    new_balance = models.DecimalField(max_digits=8, decimal_places=2, default=0, validators=[MinValueValidator(0)])
    transaction_type = models.CharField(max_length=50, null=False, choices=TransactionTypes.choices)
    

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.title

moneyaccount/forms/accounts.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from moneyaccount.models import MoneyAccount


class RegistrationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ("email", "username", "first_name", "last_name", 'password1', 'password2')

class MoneyAccountForm(forms.ModelForm):
    
    class Meta:
        model = MoneyAccount
        fields = ("name", "total_balance", "bank", "account_type", "is_main")

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args,**kwargs)

        self.user = user
        self.fields['is_main'].label = 'make main account'
        self.fields['total_balance'].widget.attrs['min'] = 0

    def clean(self):
        """Validate fields"""
        super().clean()

        initial_errors = self.errors.as_data()
        name = self.cleaned_data['name']

        if "is_main" not in initial_errors:
            is_main = self.cleaned_data['is_main']

            my_accounts = MoneyAccount.objects.filter(user=self.user)
            my_main_accounts = my_accounts.filter(is_main=True)
            same_name_accounts = my_accounts.filter(name__iexact=name)

            if 'create' in self.data:
                if is_main and my_main_accounts:
                    self.add_error("is_main", "Can't have more than 1 account as a main account")

                if name and same_name_accounts:
                    self.add_error('name', 'you already have an account with the same name.')


            if 'update' in self.data:
                if is_main and my_main_accounts.exclude(pk=self.instance.id):
                    self.add_error("is_main", "Can't have more than 1 account as a main account")

                if name and same_name_accounts.exclude(pk=self.instance.id):
                    self.add_error('name', 'you already have an account with the same name.')

moneyaccount/forms/filters.py
from django import forms


class TransactionFilterForm(forms.Form):

    filter = forms.CharField(max_length=15, required=False)
    search = forms.CharField(max_length=255, required=False)

    class Meta:
        fields = ("filter", "search")

    def clean(self):
        super().clean()

        choices = ["month", "week", 'today']
        initial_errors = self.errors.as_data()

        if "filter" not in initial_errors:
            filter = self.cleaned_data["filter"]
            if filter not in choices and filter:
                self.add_error("filter", "Invalid Choice")

moneyaccount/forms/transactions.py
import datetime
from django import forms

from moneyaccount.models import Transaction


class TransactionForm(forms.ModelForm):
    
    class Meta:
        model = Transaction
        fields = ("title", "note", "amount", "date")

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        self.fields['amount'].widget.attrs['min'] = 0
        self.fields['date'].initial = datetime.datetime.today()
        today = datetime.datetime.today()
        self.fields['date'].widget = forms.DateInput(attrs={'type': 'date', 'value':today})

moneyaccount/views/accounts.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib import messages

from moneyaccount.forms.accounts import MoneyAccountForm
from moneyaccount.models import MoneyAccount


# Money Account
class MoneyAccountListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = MoneyAccount
    template_name = 'moneyaccount/account_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def test_func(self):
        my_accounts = self.get_queryset()
        my_accounts_check = [ account.user == self.request.user for account in my_accounts]
        return all(my_accounts_check)

class MoneyAccountCreateView(LoginRequiredMixin, CreateView):
    model = MoneyAccount
    form_class = MoneyAccountForm
    template_name = 'moneyaccount/account_create.html'
    success_url = reverse_lazy('mc:account-list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()

        # Success message 
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Account Created!'
        ) 
        return super().form_valid(form)

class MoneyAccountUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = MoneyAccount
    form_class = MoneyAccountForm
    template_name = 'moneyaccount/account_update.html'
    success_url = reverse_lazy('mc:account-list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        name = form.cleaned_data['name']

        # Success message 
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f'Account({name}) Updated!'
        ) 
        return super().form_valid(form)

    def test_func(self):
        account = self.get_object()
        return True if self.request.user == account.user else False

class MoneyAccountDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = MoneyAccount
    template_name = 'moneyaccount/account_detail.html'

    def test_func(self):
        account = self.get_object()
        return True if self.request.user == account.user else False

class MoneyAccountDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = MoneyAccount
    template_name = 'moneyaccount/account_delete.html'

    def test_func(self):
        account = self.get_object()
        return True if self.request.user == account.user else False

    def get_success_url(self):
        return reverse_lazy('mc:account-list')

def make_main(request, account_pk):
    account = get_object_or_404(MoneyAccount, id=account_pk)
    main_account = MoneyAccount.objects.get(user=account.user, is_main=True)
    
    if main_account:
        main_account.is_main = False
        main_account.save()
    
    account.is_main = True
    account.save()

    return redirect(reverse_lazy("mc:account-detail", kwargs={'name':account.name, "pk":account_pk}))

moneyaccount/views/dashboard.py
import datetime
import imp
from threading import main_thread
from unicodedata import decimal
from urllib import request
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages

from moneyaccount.forms.filters import TransactionFilterForm
from moneyaccount.forms.accounts import RegistrationForm
from moneyaccount.models import MoneyAccount, Transaction


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'
    
    def get_context_data(self, **kwargs):
        """get context"""
        context = super().get_context_data(**kwargs)

        valid = False
        try:
            all_transactions = Transaction.objects.filter(account__user=self.request.user)
            main_moneyaccount = MoneyAccount.objects.get(Q(is_main=True) & Q(user=self.request.user))
        except MoneyAccount.DoesNotExist:
            main_moneyaccount = None

        form = TransactionFilterForm(self.request.GET.dict())
        if form.is_valid():
            valid = True
            
            filter = form.cleaned_data["filter"]
            search = form.cleaned_data["search"]

            if filter == "today":
                date = datetime.date.today()
                all_transactions = all_transactions.filter(date__gte=date)

            if filter == "week":
                date = datetime.date.today() - datetime.timedelta(days=7)
                all_transactions = all_transactions.filter(date__gte=date)

            if filter == "month":
                date = datetime.date.today() - datetime.timedelta(days=30)
                all_transactions = all_transactions.filter(date__gte=date)

            if search:
                all_transactions =all_transactions.filter(
                    Q(title__icontains=search) |
                    Q(amount__icontains=search) | 
                    Q(account__name__icontains=search)
                )

        context["transactions"] = all_transactions[:15]
        context["main_account"] = main_moneyaccount
        context["valid"] = valid
        return context

class UserCreateView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('mc:login')

    def form_valid(self, form):
        user = form.save(self.request)

        # Success message 
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'User Created!'
        ) 
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(reverse_lazy('mc:dashboard'))
        return super().dispatch(request, *args, **kwargs)

moneyaccount/views/reports.py
import csv
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from moneyaccount.models import MoneyAccount, Transaction


class ExportTransactionListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = MoneyAccount
    template_name = "reports.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def test_func(self):
        my_accounts = self.get_queryset()
        my_accounts_check = [ account.user == self.request.user for account in my_accounts]
        return all(my_accounts_check)

class ExportTransactionView(LoginRequiredMixin, View):
    """Generate CSV file for Transactions"""

    template_name = "transaction/export_transaction.html"
    TRANSACTION_HEADER = [
        'Account Name',
        "Title",
        "Note",
        "Current Balance",
        "Amount",
        "Total",
        "Date",
        "Transaction Type",
    ]

    def get(self, request, *args, **kwargs):
        """get context"""
        context = {
            "accounts": MoneyAccount.objects.filter(user=self.request.user),
        }
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        accounts = MoneyAccount.objects.filter(user=self.request.user)

        for account in accounts:
            if account.name in request.POST:
                file_name = f"{account.name}.csv"
                transactions = account.transactions.order_by("date")
                
                response = None
                if transactions:
                    response = HttpResponse(content_type="text/csv; charset=utf-8-sig")
                    writer = csv.writer(response)
                    writer.writerow(self.TRANSACTION_HEADER)

                    for transaction in transactions:
                        writer.writerow(
                            [
                                account.name,
                                transaction.title,
                                transaction.note,
                                transaction.current_balance,
                                transaction.amount,
                                transaction.new_balance,
                                transaction.date,
                                transaction.transaction_type,
                            ]
                        )

                    response["Content-Disposition"] = f"attachment; filename={file_name}"
                    return response
            return redirect(reverse_lazy("mc:report-list"))

templates/moneyaccount/account_create.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block title %}Create Account{% endblock %}

{% block nav-title %}Create Account{% endblock %}



{% block content %}

<div class="row justify-content-center my-5">
    <div class="col-lg-7 col-md-12 col-sm-12">
        <div class="card bg-light form-card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" name="create" class="btn btn-primary col-12 my-1 fw-bold">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/moneyaccount/account_delete.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block title %}Delete Account{% endblock %}

{% block nav-title %}Delete Account ({{object.name|title}}){% endblock %}



{% block content %}

<div class="row justify-content-center my-5">
    <div class="col-lg-7 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="py-4 px-4 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                    <h4 class="fw-bold ">Delete</h4>
                    <hr>
                    <h5 class="fw-bold">are you sure you want to delete your account?</h5>
                    <h6 class="fw-bold text-muted">this action is irreversible </h6>
                </div>

                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" name="update" class="btn btn-danger col-12 my-1 fw-bold">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/moneyaccount/account_detail.html
{% extends '../base.html' %}
{% load static%}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}

{% block title %}{{object.name}}{% endblock %}

{% block nav-title %}
    {% if object.is_main %}
        <i class="bi bi-bookmark-star-fill"></i>
    {% endif %}
    {{object.name}}
{% endblock %}

{% block nav-buttons %}
    <a href="{% url 'mc:account-delete' object.name object.id %}" class="mx-1 btn btn-danger fw-bold">Delete</a>
    <a href="{% url 'mc:account-update' object.name object.id %}" class="mx-1 btn btn-primary fw-bold">Edit</a>
    <a class="btn btn-primary fw-bold" href="{% url 'mc:transaction-list' object.name object.id %}">My Transactions</a>
{% endblock %}

{% block content %}

<div class="d-flex mt-5 row py-3 justify-content-around mt-5">
    {% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} text-center">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5 mt-2 main-card bg-light">
        <div class="py-4 px-4 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
            <h4 class="fw-bold ">Total Balance</h4>
            <hr>
            <h5 class="fw-bold text-primary">{{object.total_balance}}</h5>
        </div>
    </div>

    <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
        <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
            <h4 class="fw-bold ">Total Transactions</h4>
            <hr>
            <h5 class="fw-bold text-primary">{{object.transactions.count}}</h5>
        </div>
    </div>

    <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
        <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
            {% if object.is_main %}
                <h4 class="fw-bold">
                    Main Account
                </h4>
                <hr>
                <h5 class="fw-bold ">
                    <i class="bi bi-bookmark-star-fill"></i>
                </h5>
            {% else %}
                <h4 class="fw-bold">
                    <a class="text-decoration-none text-danger" href="{% url 'mc:make-main' object.id %}">Make Main Account</a>
                </h4>
                <hr>
                <h5 class="fw-bold ">
                    <i class="bi bi-bookmark-star-fill"></i>
                </h5>
            {% endif %}
        </div>
    </div>

    <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
        <div class="py-4 px-4 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
            <h4 class="fw-bold ">Account Type</h4>
            <hr>
            <h5 class="fw-bold text-primary">{{object.get_account_type_display}}</h5>
        </div>
    </div>

    <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
        <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
            <h4 class="fw-bold ">Bank</h4>
            <hr>
            <h5 class="fw-bold text-primary">{{object.bank}}</h5>
        </div>
    </div>

    <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
        <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
            <h4 class="fw-bold ">Latest Transaction</h4>
            <hr>
            <h5 class="fw-bold text-primary">{{object.transactions.last.date}}</h5>
        </div>
    </div>

</div>

{% endblock %}

templates/moneyaccount/account_list.html
{% extends '../base.html' %}
{% load static%}

{% block custom-css %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}

{% block title %}Accounts{% endblock %}

{% block nav-title %}My Accounts{% endblock %}

{% block nav-buttons %}
    <a class="btn btn-primary fw-bold" href="{% url 'mc:account-create' %}">Create Account</a>
{% endblock %}

{% block content %}

    <div class="d-flex mt-5 row py-3 justify-content-around">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }} text-center">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

            
        {% if object_list %}
            {% for account in object_list %}
                <div class="col-sm-12 col-md-12 col-lg-5 px-3 mb-4 main-card bg-light">
                    {% if account.is_main %}
                        <div class="mt-1">
                            <i class="bi bi-bookmark-star-fill main-icon"></i>
                        </div>
                    {% endif %}

                    <div class="py-4 px-4 my-2 text-center detail h-50 {% if not account.is_main %}mt-5{% endif %}">
                        <ul class="account-info">
                            <li><b>{{account.name|title}}</b></li>
                            <li class="{% if account.total_balance < 0 %}text-danger{% else %}text-success{% endif %}"><b>{{account.total_balance}}</b></li>
                            <hr>
                            <li><b>{{account.get_account_type_display}} Account</b></li>
                        </ul>
                        <div class="mt-5 row justify-content-around">
                            <a href="{% url 'mc:account-update' account.name account.id %}" class="col-md-12 col-sm-12 col-lg-5 mb-1 btn btn-primary fw-bold" type="button">Edit</a>
                            <a href="{% url 'mc:account-detail' account.name account.id %}" class="col-md-12 col-sm-12 col-lg-5 mb-1 btn btn-primary fw-bold" type="button">Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h2 class="text-danger text-center card p-5 bg-light mt-5">No Accounts Available...</h2>
        {% endif %}
                
    </div>

{% endblock %}

templates/moneyaccount/account_update.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block title %}Update Account{% endblock %}

{% block nav-title %}Update Account ({{object.name|title}}){% endblock %}



{% block content %}

<div class="row justify-content-center my-5">
    <div class="col-lg-7 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" name="update" class="btn btn-primary col-12 my-1 fw-bold">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}