core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moneyaccount.urls', namespace="mc"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

moneyaccount/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from moneyaccount.views import dashboard, accounts, transactions, reports


app_name = "mc"

urlpatterns = [
    path('dashboard/', dashboard.DashboardView.as_view(), name="dashboard"),
    # Money Accounts
    path('my-accounts/', accounts.MoneyAccountListView.as_view(), name="account-list"),
    path('my-accounts/create/', accounts.MoneyAccountCreateView.as_view(), name="account-create"),
    path('my-accounts/update/<str:name>/<uuid:pk>/', accounts.MoneyAccountUpdateView.as_view(), name="account-update"),
    path('my-accounts/<str:name>/<uuid:pk>/', accounts.MoneyAccountDetailView.as_view(), name="account-detail"),
    path('my-accounts/delete/<str:name>/<uuid:pk>/', accounts.MoneyAccountDeleteView.as_view(), name="account-delete"),
    path('make-main/<uuid:account_pk>/', accounts.make_main, name="make-main"),
    # Transactions
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/', transactions.TransactionListView.as_view(), name="transaction-list"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/create/', transactions.TransactionCreateView.as_view(), name="transaction-create"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/delete/<uuid:pk>', transactions.TransactionDeleteView.as_view(), name="transaction-delete"),
    path('my-accounts/<str:name>/<uuid:account_pk>/transactions/detail/<uuid:pk>', transactions.TransactionDetailView.as_view(), name="transaction-detail"),
    # Export Reports
    path('reports/', reports.ExportTransactionListView.as_view(), name="report-list"),
    path('reports/export/<uuid:account_pk>/', reports.ExportTransactionView.as_view(), name="export-report"),
    # User Accounts
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True) ,name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', dashboard.UserCreateView.as_view(), name='register'),
]

templates/transaction/transaction_create.html
{% extends '../base.html' %}
{% load static%}
{% load crispy_forms_tags %}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block title %}Make Transaction{% endblock %}

{% block nav-title %}Make Transaction{% endblock %}

{% block content %}

    <div class="row justify-content-center my-5">
        <div class="col-lg-7 col-md-12 col-sm-12">
            <div class="card bg-light form-card">
                <div class= "p-4 text-center">
                    <h5><b>Account: </b> {{account}}</h5>
                    <h5><b>Total_balance: </b> {{account.total_balance}}</h5>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{form|crispy}}
                        <hr>
                        <button type="submit" name="payment" class="btn btn-danger col-12 my-1 fw-bold">Payment</button>
                        <button type="submit" name="deposit" class="btn btn-dark col-12 my-1 fw-bold">Deposit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/transaction/transaction_detail.html
{% extends '../base.html' %}
{% load static%}

{% block custom-css %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}

{% block title %}{{object.title}}{% endblock %}

{% block nav-title %} <a class="text-dark text-decoration-none" href="{% url 'mc:transaction-list' view.kwargs.name view.kwargs.account_pk %}">Transactions</a> / {{object.title}} {% endblock %}

{% block content %}
    <div class="d-flex mt-5 row py-3 justify-content-around mt-5">

        <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
            <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                <h4 class="fw-bold ">Title</h4>
                <hr>
                <h5 class="fw-bold text-primary">{{object.title}}</h5>
            </div>
        </div>

        <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
            <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                <h4 class="fw-bold ">Note</h4>
                <hr>
                <h5 class="fw-bold text-primary">{{object.note}}</h5>
            </div>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
            <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                <h4 class="fw-bold ">Amount</h4>
                <hr>
                <h5 class="fw-bold text-primary">{{object.amount}}</h5>
            </div>
        </div>

        <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
            <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                <h4 class="fw-bold ">Date</h4>
                <hr>
                <h5 class="fw-bold text-primary">{{object.date}}</h5>
            </div>
        </div>

        <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
            <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                <h4 class="fw-bold ">Account</h4>
                <hr>
                <h5 class="fw-bold text-primary">{{object.account}}</h5>
            </div>
        </div>

        <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
            <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                <h4 class="fw-bold ">Current Balance</h4>
                <hr>
                <h5 class="fw-bold text-primary">{{object.current_balance}}</h5>
            </div>
        </div>

        <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
            <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                <h4 class="fw-bold ">Total</h4>
                <hr>
                <h5 class="fw-bold text-primary">{{object.new_balance}}</h5>
            </div>
        </div>

        <div class="col-sm-12 col-md-4 col-lg-3 px-3 mx-1 mb-5  mt-2 main-card bg-light">
            <div class="py-4 px-2 my-2 text-center detail {% if not object.is_main %}mt-5{% endif %}">
                <h4 class="fw-bold ">Type</h4>
                <hr>
                <h5 class="fw-bold text-primary">{{object.transaction_type}}</h5>
            </div>
        </div>
    </div>

{% endblock %}

templates/transaction/transaction_list.html
{% extends '../base.html' %}
{% load static%}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}

{% block title %}{{view.kwargs.name}} - Transactions{% endblock %}

{% block nav-title %} <a class="text-dark text-decoration-none" href="{% url 'mc:account-detail' view.kwargs.name view.kwargs.account_pk %}">{{view.kwargs.name}}</a> / Transactions {% endblock %}

{% block nav-buttons %}
    {% include 'filter.html' %} 
    <a class="btn btn-primary fw-bold my-1" href="{% url 'mc:transaction-create' view.kwargs.name view.kwargs.account_pk %}">Make Transaction</a>
{% endblock %}

{% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} text-center">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

    <div class="table-responsive my-5">
        {% if object_list %} 
            <table class="table table-hover table-striped table-sm mb-5 text-center">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Current Balance</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Total</th>
                        <th scope="col">Date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for transaction in object_list %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{transaction.title}}</td>
                        <td class="{% if transaction.transaction_type == 'payment' %}text-danger{% else %}text-success{% endif %}">{{transaction.current_balance}}</td>
                        <td class="{% if transaction.transaction_type == 'payment' %}text-danger{% else %}text-success{% endif %}">{{transaction.amount}}</td>
                        <td class="{% if transaction.transaction_type == 'payment' %}text-danger{% else %}text-success{% endif %}">{{transaction.new_balance}}</td>
                        <td>{{transaction.date}}</td>
                        <td>
                            <a href="{% url 'mc:transaction-detail' transaction.account.name transaction.account.id transaction.id %}" class="btn btn-sm btn-dark m-1"><i class="bi bi-arrow-up-right-square-fill"></i></a>
                            <form action="{% url 'mc:transaction-delete' transaction.account.name transaction.account.id transaction.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-danger m-1"><i class="bi bi-x-square-fill"></i></button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            {% if object_list is None %}
                <h2 class="text-danger text-center card p-5 bg-light mt-5">Invalid Search Bro...</h2>
            {% else %}
                <h2 class="text-danger text-center card p-5 bg-light mt-5">No Transactions Available...</h2>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}